title: Yongbin Feng
position: Assistant Professor of Physics
affiliation: Texas Tech University
email: yongbin.feng (at) ttu.edu
keywords: minimal academic
github_link: https://github.com/yongbinfeng
avatar: ./assets/img/yongbin_feng.png
favicon: ./assets/img/w_decay.jpg
favicon_dark: ./assets/img/w_decay.jpg
description: Yongbin Feng's homepage
canonical: https://yongbinfeng.github.io
remote_theme: yaoyao-liu/minimal-light
